server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://ep-square-fog-a4nspwnd-pooler.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_3T7oxhfDauUC&sslmode=require
    username: neondb_owner
    password: npg_3T7oxhfDauUC
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100000MB
      max-request-size: 100000MB

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
api:
  prefix: api/v1

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=



momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  endpoint-url: https://test-payment.momo.vn/v2/gateway/api/create
  return-url: https://random-id.ngrok.io/api/v1/payments/momo/success
  notify-url: https://random-id.ngrok.io/api/v1/payments/momo/notify


logging:
  level:
    org.springframework.security: DEBUG
vnpay:
    tmnCode: 0D7U0C4Z
    hashSecret: 8ZF37DFFNM6F4M756V6PA2MW4UO75DM4
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: https://710c-171-251-1-165.ngrok-free.app/api/v1/payments/vnpay-return

cloudinary:
  cloud_name: diauyc0ws
  api_key: 118664976699364
  api_secret: G701wrbBkdMtBvFTT6e5xo7lglk
# VN pay
#  vnpay.tmnCode=0D7U0C4Z
#  vnpay.hashSecret=8ZF37DFFNM6F4M756V6PA2MW4UO75DM4
#  vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#  vnpay.returnUrl=https://e753-113-185-105-221.ngrok-free.app/api/payment/vnpay-return
#  sandbox.vnpayment.vn
